### ISSUE TITLE
Main window not opening while GPose is active

### ISSUE THREAD

**Issue by Lucsmat** [ViviAshe/XIVSnapper#1]
Not sure if it is because of Glamourer's new update (I hadn't checked for updates in a bit so not sure if it's new or not either) or something else, but the main window (that opens when typing /psnap) does not open/stays open in GPose. (Nor can it be opened from the the installed mods menu, and typing /psnap while GPose is active also does not work)

**Comment by ViviAshe** [comment]
I'll take a look. Nothing should have been changed there UI wise.

**Comment by ViviAshe** [comment]
Pushed on the 0.0.0.6 release. Thank you for bringing this to my attention.
